SongDew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:poll_id>/', views.detail, name="detail"),
    path('<int:poll_id>/results/', views.results, name="results"),
    path('<int:poll_id>/<int:choice_id>/vote/', views.vote, name="vote"),
    path('accounts/login', views.Login.as_view(), name="login"),
    path('accounts/register', views.Register.as_view(), name="register"),
    path('profile', views.profile, name="profile"),
    path('accounts/logout', views.logout_view, name="logout"),
    path('create/', views.Create.as_view(), name="create"),
    path('add/choice/<int:poll_id>', views.AddChoice.as_view(), name="add_choice"),
    path('past', views.past, name="past"),
    path('polls/remove/<int:poll_id>', views.remove, name="remove"),
    path('polls/end/<int:poll_id>', views.end, name="end"),
    path('polls/search', views.search, name="search"),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    picture = models.BinaryField(null=True, editable=True)

    def __str__(self):
        return self.username

class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False, related_name="started_by")
    content = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    expiry = models.DateTimeField(help_text="Format: YYYY-MM-DD HOURS:MINUTES:SECONDS, example - 2021-10-16 19:30:51", blank=True, null=True)
    active = models.BooleanField(default=True)
    public = models.BooleanField(default=False)
    voted = models.ManyToManyField(User)

    def __str__(self):
        return self.content

class Choice(models.Model):
    text = models.TextField()
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

polls/forms.py
from django import forms

from .models import User, Choice, Poll

"""
class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Cofirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            return False
        return True

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
"""

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['content', 'expiry', 'public']

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['text']

polls/views.py
from django.utils import timezone
from datetime import timedelta
from .models import User, Poll, Choice

from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import PollForm, ChoiceForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    polls = Poll.objects.filter(active=True, public=True)
    if request.user.is_authenticated:
        polls = Poll.objects.filter(active=True)
        for poll in polls:
            if poll.expiry:
                if poll.expiry <= timezone.now():
                    poll.active=False
                    poll.save()
        return render(request, "polls/index.html", {
            'polls': Poll.objects.filter(active=True),
            'h': "Active Polls",
        })
    for poll in polls:
        if poll.expiry <= timezone.now():
            poll.active=False
            poll.save()
    return render(request, "polls/index.html", {
        'polls': Poll.objects.filter(active=True, public=True),
        'h': "Active Polls",
    })

def past(request):
    polls = Poll.objects.all()
    if request.user.is_authenticated:
        polls = Poll.objects.filter(active=False)
    else:
        polls = Poll.objects.filter(active=False, public=True)
    return render(request, "polls/index.html", {
        'polls': polls,
        'h': "Past Polls",
    })

class Register(View):
    template = 'polls/register.html'
    success_url = 'polls:index'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        email = request.POST["email"]
        p1 = request.POST["password"]
        p2 = request.POST["password_repeat"]
        if not p1 == p2:
            return render(request, self.template, {
                'error':'Passwords do not match'
            })
        try:
            user = User.objects.create_user(username, email, p1)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, self.template, {
                "message": "Email address or username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse(self.success_url))

class Login(View):
    template = 'polls/login.html'
    success_url = 'polls:index'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse(self.success_url))
        else:
            return render(request, self.template, {
                "error": "Invalid username and/or password."
            })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:index'))

def detail(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    done = False
    if request.user in poll.voted.all():
        done = True
    return render(request, "polls/detail.html", {
        'poll': poll,
        'choices': Choice.objects.filter(poll=poll),
        'done': done,
        'time_left': poll.expiry - timezone.now(),
    })

class Create(LoginRequiredMixin, View):
    template = "polls/create.html"
    success_url = 'polls:detail'

    def get(self, request):
        form = PollForm()
        return render(request, self.template, {
            'form': form,
            'render_time': timezone.now()
        })

    def post(self, request):
        form = PollForm(request.POST)
        if form.is_valid():
            instance = form.save()
            instance.owner = request.user
            if not instance.expiry:
                instance.expiry = instance.pub_date + timedelta(minutes = 5)
            instance.save()
            return HttpResponseRedirect(reverse(self.success_url, kwargs={'poll_id':instance.id, }))

        return render(request, self.template, {
            'form': PollForm(),
            'render_time': timezone.now(),
            'error': 'Something went Wrong!'
        })

def results(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    choices = Choice.objects.filter(poll=poll).order_by('-votes')

    return render(request, "polls/results.html", {
        'choices': choices,
    })

class AddChoice(LoginRequiredMixin, View):
    template = "polls/choice.html"
    success_url = "polls:detail"

    def get(self, request, poll_id):
        poll = Poll.objects.get(id=poll_id)
        form = ChoiceForm()
        return render(request, self.template, {
            'form': form,
            'poll': poll,
        })

    def post(self, request, poll_id):
        form = ChoiceForm(request.POST)
        poll = Poll.objects.get(id=poll_id)
        if form.is_valid():
            instance = form.save()
            instance.poll = poll
            instance.save()
            poll.expiry = poll.expiry + timedelta(minutes = 5)
            poll.save()
            return HttpResponseRedirect(reverse(self.success_url, kwargs={'poll_id':poll_id, }))

        return render(request, self.template, {
            'form': form,
            'error': 'Something went wrong, plese try again',
        })

def vote(request, poll_id, choice_id):
    poll = Poll.objects.get(id=poll_id)
    choice = Choice.objects.get(id=choice_id)

    if poll.expiry > timezone.now():
        poll.voted.add(request.user)
        poll.save()

        choice.votes = choice.votes + 1
        choice.save()


        return HttpResponseRedirect(reverse('polls:results', kwargs={'poll_id':poll_id, }))

    return HttpResponseRedirect(reverse('polls:detail', kwargs={'poll_id':poll_id, }))

@login_required
def profile(request):
    polls = Poll.objects.filter(owner=request.user)
    return render(request, "polls/profile.html", {
        'polls': polls
    })

@login_required
def remove(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    poll.delete()
    return HttpResponseRedirect(reverse('polls:index'))

def end(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    if poll.owner == request.user:
        poll.active = False
        poll.save()
        return HttpResponseRedirect(reverse('polls:index'))
    return HttpResponse("Invalid Request!!")

def search(request):
    query = request.POST['search_input']
    output = []
    polls = Poll.objects.all()
    for poll in polls:
        if query in poll.content:
            output.append(poll)

    return render(request, "polls/index.html", {
        'h': "Search Results",
        'polls': output,
    })

polls/templates/polls/choice.html
{% extends 'layout.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  Add choices
{% endblock %}

{% block heading %}
  {{ poll.content }}
{% endblock %}

{% block main %}
  <br>
  Add choices for this poll: <br>

  <form action="{% url 'polls:add_choice' poll.id %}" method="post">
    {% csrf_token %}
    {{ form | crispy }}
    {{ error }}
    <br>
    <input type="submit" name="add" value="ADD">
  </form>

{% endblock %}

polls/templates/polls/create.html
{% extends 'layout.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  Create a Poll
{% endblock %}

{% block heading %}
  Create a Poll
{% endblock %}

{% block main %}
  Render Time = {{ render_time }}
  <form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <br>
    <input type="submit" name="create" value="Create">
  </form>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'layout.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  Poll
{% endblock %}

{% block heading %}
  {{ poll.content }}
{% endblock %}

{% block main %}
  Voting Complete on - {{ poll.expiry }}
  <br>
  {% if poll.active %}
  Time left:
    {{ time_left }}
  {% endif %}
  <br><br>
  {% if poll.active %}
  {% if not done %}
  Select one of the following options to vote: <br>
  {% for choice in choices %}
    <ul>
      <li><a href="{% url 'polls:vote' poll.id choice.id %}">{{ choice.text }}</a></li>
      <br>
    </ul>
  {% endfor %}
  {% else %}
    You have Already voted for this poll <br>
    <hr>
    <a href="{% url 'polls:results' poll.id %}">See stats and results</a>
  {% endif %}
<br><br>
  {% if poll.owner == request.user %}
    <a href="{% url 'polls:add_choice' poll.id %}">Add more choices?</a>
    <br>
  {% endif %}
  {% else %}
  This poll has ended <br>
  <a href="{% url 'polls:results' poll.id %}">See stats and results</a>
  {% endif %}

  {% if poll.owner == request.user %}
  <br>
    <a href="{% url 'polls:remove' poll.id %}">Remove This POLL</a> This Action Cannot be Undone
    <br>
    <a href="{% url 'polls:end' poll.id %}">End Voting for This POLL</a>
  {% endif %}

{% endblock %}

polls/templates/polls/index.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Polls Home
{% endblock %}

{% block heading %}
  {{ h }}
{% endblock %}

{% block  main %}
  <br>
  {% for poll in polls %}
    <a href="{% url 'polls:detail' poll.id %}">{{ poll.content }}</a>
    <br>By - {{ poll.owner.username }} on {{ poll.pub_date }}
    <br>
  {% endfor %}
{% endblock %}

polls/templates/polls/login.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Login
{% endblock %}

{% block nav %}

{% endblock %}

{% block body %}
<body class="bg-gradient-primary">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-9 col-lg-12 col-xl-10">
              <div class="card shadow-lg o-hidden border-0 my-5">
                  <div class="card-body p-0">
                      <div class="row">
                          <div class="col-lg-6 d-none d-lg-flex">
                              <div class="flex-grow-1 bg-login-image">
                                <div class="tenor-gif-embed" data-postid="16043627" data-share-method="host" data-aspect-ratio="1" data-width="100%"><a href="https://tenor.com/view/hello-there-private-from-penguins-of-madagascar-hi-wave-hey-there-gif-16043627">Hello There Private From Penguins Of Madagascar GIF</a>from <a href="https://tenor.com/search/hello+there-gifs">Hello There GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
                              </div>
                          </div>
                          <div class="col-lg-6">
                              <div class="p-5">
                                  <div class="text-center">
                                      <h4 class="text-dark mb-4">Welcome Back!</h4>
                                  </div>
                                  <form class="user" action="{% url 'polls:login' %}" method="post">
                                    {% csrf_token %}
                                      <div class="mb-3"><input class="form-control form-control-user" type="username" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Username..." name="username"></div>
                                      <div class="mb-3"><input class="form-control form-control-user" type="password" id="exampleInputPassword" placeholder="Password" name="password"></div>
                                      <br>
                                      </div>
                                      <input type="submit" name="login" value="Login" class="btn btn-primary d-block btn-user w-100" />
                                      <hr>
                                  </form>
                                  <div class="text-center"><a class="small" href="{% url 'polls:register' %}">Create an Account!</a></div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</body>
{% endblock %}

polls/templates/polls/profile.html
{% extends 'layout.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  {{ request.user.username }}
{% endblock %}

{% block heading %}
  {{ request.user.username }}
{% endblock %}

{% block main %}
Polls by you: <br>
<div class="row">
  <ul>
    {% for poll in polls %}
      <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.content }}</a></li>
      <br>
    {% endfor %}
  </ul>
</div>
{% endblock %}

polls/templates/polls/register.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Register
{% endblock %}

{% block nav %}

{% endblock %}

{% block body %}
  <body class="bg-gradient-primary">
    <div class="container">
        <div class="card shadow-lg o-hidden border-0 my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-flex">
                        <div class="flex-grow-1 bg-register-image">
                          <div class="tenor-gif-embed" data-postid="15830260" data-share-method="host" data-aspect-ratio="1.3617" data-width="100%"><a href="https://tenor.com/view/spongebob-welcome-happy-rainbow-gif-15830260">Spongebob Welcome GIF</a>from <a href="https://tenor.com/search/spongebob-gifs">Spongebob GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h4 class="text-dark mb-4">Create an Account!</h4>
                            </div>
                            <form class="user", method="post" action="{% url 'polls:register' %}">
                              {% csrf_token %}
                                <div class="row mb-3">
                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="exampleFirstName" placeholder="First Name" name="first_name"></div>
                                    <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="exampleFirstName" placeholder="Last Name" name="last_name"></div>
                                </div>
                                <div class="mb-3"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email Address" name="email"></div>
                                <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Username" name="username"></div>
                                <div class="row mb-3">
                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="password" id="examplePasswordInput" placeholder="Password" name="password"></div>
                                    <div class="col-sm-6"><input class="form-control form-control-user" type="password" id="exampleRepeatPasswordInput" placeholder="Repeat Password" name="password_repeat"></div>
                                    {{ error }}
                                    <br>
                                </div><input class="btn btn-primary d-block btn-user w-100" type="submit" value="Register Account" />
                                <hr>
                            </form>
                            <div class="text-center"></div>
                            <div class="text-center"><a class="small" href="{% url 'polls:login' %}">Already have an account? Login!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </body>
{% endblock %}

polls/templates/polls/results.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
  Result and Stats
{% endblock %}

{% block heading %}
  {{ poll.content }}
{% endblock %}

{% block main %}
  <br>
  These are the voting trends for this poll: <br>
  {% for choice in choices %}
    <ul>
      <li>{{ choice.text }} - {{ choice.votes }} votes</li>
      <br>
    </ul>
  {% endfor %}
<br><br>

{% endblock %}