SongDew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:poll_id>/', views.detail, name="detail"),
    path('<int:poll_id>/results/', views.results, name="results"),
    path('<int:poll_id>/<int:choice_id>/vote/', views.vote, name="vote"),
    path('accounts/login', views.Login.as_view(), name="login"),
    path('accounts/register', views.Register.as_view(), name="register"),
    path('profile', views.profile, name="profile"),
    path('accounts/logout', views.logout_view, name="logout"),
    path('create/', views.Create.as_view(), name="create"),
    path('add/choice/<int:poll_id>', views.AddChoice.as_view(), name="add_choice"),
    path('past', views.past, name="past"),
    path('polls/remove/<int:poll_id>', views.remove, name="remove"),
    path('polls/end/<int:poll_id>', views.end, name="end"),
    path('polls/search', views.search, name="search"),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    picture = models.BinaryField(null=True, editable=True)

    def __str__(self):
        return self.username

class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False, related_name="started_by")
    content = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    expiry = models.DateTimeField(help_text="Format: YYYY-MM-DD HOURS:MINUTES:SECONDS, example - 2021-10-16 19:30:51", blank=True, null=True)
    active = models.BooleanField(default=True)
    public = models.BooleanField(default=False)
    voted = models.ManyToManyField(User)

    def __str__(self):
        return self.content

class Choice(models.Model):
    text = models.TextField()
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

polls/forms.py
from django import forms

from .models import User, Choice, Poll

"""
class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Cofirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            return False
        return True

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
"""

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['content', 'expiry', 'public']

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['text']

polls/views.py
from django.utils import timezone
from datetime import timedelta
from .models import User, Poll, Choice

from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import PollForm, ChoiceForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    polls = Poll.objects.filter(active=True, public=True)
    if request.user.is_authenticated:
        polls = Poll.objects.filter(active=True)
        for poll in polls:
            if poll.expiry:
                if poll.expiry <= timezone.now():
                    poll.active=False
                    poll.save()
        return render(request, "polls/index.html", {
            'polls': Poll.objects.filter(active=True),
            'h': "Active Polls",
        })
    for poll in polls:
        if poll.expiry <= timezone.now():
            poll.active=False
            poll.save()
    return render(request, "polls/index.html", {
        'polls': Poll.objects.filter(active=True, public=True),
        'h': "Active Polls",
    })

def past(request):
    polls = Poll.objects.all()
    if request.user.is_authenticated:
        polls = Poll.objects.filter(active=False)
    else:
        polls = Poll.objects.filter(active=False, public=True)
    return render(request, "polls/index.html", {
        'polls': polls,
        'h': "Past Polls",
    })

class Register(View):
    template = 'polls/register.html'
    success_url = 'polls:index'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        email = request.POST["email"]
        p1 = request.POST["password"]
        p2 = request.POST["password_repeat"]
        if not p1 == p2:
            return render(request, self.template, {
                'error':'Passwords do not match'
            })
        try:
            user = User.objects.create_user(username, email, p1)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, self.template, {
                "message": "Email address or username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse(self.success_url))

class Login(View):
    template = 'polls/login.html'
    success_url = 'polls:index'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse(self.success_url))
        else:
            return render(request, self.template, {
                "error": "Invalid username and/or password."
            })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:index'))

def detail(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    done = False
    if request.user in poll.voted.all():
        done = True
    return render(request, "polls/detail.html", {
        'poll': poll,
        'choices': Choice.objects.filter(poll=poll),
        'done': done,
        'time_left': poll.expiry - timezone.now(),
    })

class Create(LoginRequiredMixin, View):
    template = "polls/create.html"
    success_url = 'polls:detail'

    def get(self, request):
        form = PollForm()
        return render(request, self.template, {
            'form': form,
            'render_time': timezone.now()
        })

    def post(self, request):
        form = PollForm(request.POST)
        if form.is_valid():
            instance = form.save()
            instance.owner = request.user
            if not instance.expiry:
                instance.expiry = instance.pub_date + timedelta(minutes = 5)
            instance.save()
            return HttpResponseRedirect(reverse(self.success_url, kwargs={'poll_id':instance.id, }))

        return render(request, self.template, {
            'form': PollForm(),
            'render_time': timezone.now(),
            'error': 'Something went Wrong!'
        })

def results(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    choices = Choice.objects.filter(poll=poll).order_by('-votes')

    return render(request, "polls/results.html", {
        'choices': choices,
    })

class AddChoice(LoginRequiredMixin, View):
    template = "polls/choice.html"
    success_url = "polls:detail"

    def get(self, request, poll_id):
        poll = Poll.objects.get(id=poll_id)
        form = ChoiceForm()
        return render(request, self.template, {
            'form': form,
            'poll': poll,
        })

    def post(self, request, poll_id):
        form = ChoiceForm(request.POST)
        poll = Poll.objects.get(id=poll_id)
        if form.is_valid():
            instance = form.save()
            instance.poll = poll
            instance.save()
            poll.expiry = poll.expiry + timedelta(minutes = 5)
            poll.save()
            return HttpResponseRedirect(reverse(self.success_url, kwargs={'poll_id':poll_id, }))

        return render(request, self.template, {
            'form': form,
            'error': 'Something went wrong, plese try again',
        })

def vote(request, poll_id, choice_id):
    poll = Poll.objects.get(id=poll_id)
    choice = Choice.objects.get(id=choice_id)

    if poll.expiry > timezone.now():
        poll.voted.add(request.user)
        poll.save()

        choice.votes = choice.votes + 1
        choice.save()


        return HttpResponseRedirect(reverse('polls:results', kwargs={'poll_id':poll_id, }))

    return HttpResponseRedirect(reverse('polls:detail', kwargs={'poll_id':poll_id, }))

@login_required
def profile(request):
    polls = Poll.objects.filter(owner=request.user)
    return render(request, "polls/profile.html", {
        'polls': polls
    })

@login_required
def remove(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    poll.delete()
    return HttpResponseRedirect(reverse('polls:index'))

def end(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    if poll.owner == request.user:
        poll.active = False
        poll.save()
        return HttpResponseRedirect(reverse('polls:index'))
    return HttpResponse("Invalid Request!!")

def search(request):
    query = request.POST['search_input']
    output = []
    polls = Poll.objects.all()
    for poll in polls:
        if query in poll.content:
            output.append(poll)

    return render(request, "polls/index.html", {
        'h': "Search Results",
        'polls': output,
    })

polls/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
</head>

{% block body %}
<body id="page-top">
    <div id="wrapper">
      {% block nav %}
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon rotate-n-15"></div>
                    <div class="sidebar-brand-text mx-3"><span>POLLS</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:index' %}"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:profile' %}"><i class="fas fa-user"></i><span>Profile</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:create' %}"><i class="fas"></i><span>Create Poll</span></a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'polls:past' %}"><i class="fas"></i><span>Past Polls</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:logout' %}"><i class="far fa-user-circle"></i><span>Logout</span></a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:login' %}"><i class="far fa-user-circle"></i><span>Login</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'polls:register' %}"><i class="fas fa-user-circle"></i><span>Register</span></a></li>
                    {% endif %}
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <form class="d-none d-sm-inline-block me-auto ms-md-3 my-2 my-md-0 mw-100 navbar-search" action="{% url 'polls:search' %}" method="post">
                          {% csrf_token %}
                            <div class="input-group"><input class="bg-light form-control border-0 small" type="text" name="search_input" placeholder="Search ...(Case Sensitive)">&nbsp;<i class="fas fa-search"></i></div>
                        </form>

                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><span class="d-none d-lg-inline me-2 text-gray-600 small"></span><img class="border rounded-circle img-profile" >
                                    <div class="tenor-gif-embed" data-postid="15962552" data-share-method="host" data-aspect-ratio="1.01266" data-width="100%"><a href="https://tenor.com/view/user-icons-hmm-thinking-gif-15962552">User Icons GIF</a>from <a href="https://tenor.com/search/user-gifs">User GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
                                    {{ request.user.username }}
                                </a>

                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                {% endblock %}
                <div class="container-fluid">
                    <h3 class="text-dark mb-1">{% block heading %}
                      {% endblock %}
                    </h3>
                    <br>
                    {% block main %}

                    {% endblock %}
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Made by Abhigya Shridhar</span></div>
                </div>
            </footer>
        </div>


</body>
{% endblock %}

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bs-init.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>

</html>